# Goes in ~/.tmux.conf
setw -g mode-keys vi
set-option -g default-shell /usr/bin/zsh

# # For older tmux versions:
# set -ga terminal-overrides ",*256col*:Tc"
# set -g default-terminal "screen-256color"

# For newer tmux versions:
set-option -a terminal-features 'xterm:RGB'

